# Generate KPI Card
$f = "C:\wse\OnboardAI\src\components\dashboard\kpi-card.tsx"
Remove-Item $f -Force -ErrorAction SilentlyContinue
Add-Content $f -Value "interface KpiCardProps {"
Add-Content $f -Value "  title: string;"
Add-Content $f -Value "  value: string | number;"
Add-Content $f -Value "  icon: React.ReactNode;"
Add-Content $f -Value "  trend?: { value: string; positive: boolean };"
Add-Content $f -Value "  color?: string;"
Add-Content $f -Value "}"
Add-Content $f -Value ""
Add-Content $f -Value "export function KpiCard({ title, value, icon, trend, color = "indigo" }: KpiCardProps) {"
Add-Content $f -Value "  const colors: Record<string, string> = {"
Add-Content $f -Value "    indigo: "bg-indigo-50 text-indigo-700 ring-indigo-600/20","
Add-Content $f -Value "    emerald: "bg-emerald-50 text-emerald-700 ring-emerald-600/20","
Add-Content $f -Value "    amber: "bg-amber-50 text-amber-700 ring-amber-600/20","
Add-Content $f -Value "    red: "bg-red-50 text-red-700 ring-red-600/20","
Add-Content $f -Value "    blue: "bg-blue-50 text-blue-700 ring-blue-600/20","
Add-Content $f -Value "  };"
Add-Content $f -Value "  return ("
Add-Content $f -Value "    <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">"
Add-Content $f -Value "      <div className="flex items-center justify-between">"
Add-Content $f -Value "        <div>"
Add-Content $f -Value "          <p className="text-sm font-medium text-gray-500">{title}</p>"
Add-Content $f -Value "          <p className="mt-2 text-3xl font-bold text-gray-900">{value}</p>"
Add-Content $f -Value "          {trend && ("
Add-Content $f -Value "            <p className={`mt-1 text-sm ${trend.positive ? "text-emerald-600" : "text-red-600"}`}>"
Add-Content $f -Value "              {trend.value}"
Add-Content $f -Value "            </p>"
Add-Content $f -Value "          )}"
Add-Content $f -Value "        </div>"
Add-Content $f -Value "        <div className={`rounded-lg p-3 ring-1 ring-inset ${colors[color] || colors.indigo}`}>"
Add-Content $f -Value "          {icon}"
Add-Content $f -Value "        </div>"
Add-Content $f -Value "      </div>"
Add-Content $f -Value "    </div>"
Add-Content $f -Value "  );"
Add-Content $f -Value "}"
Write-Host "kpi-card.tsx written"