# Generate App Layout
$f = "C:\wse\OnboardAI\src\components\layout\sidebar.tsx"
Remove-Item $f -Force -ErrorAction SilentlyContinue

Add-Content $f -Value "'use client';"
Add-Content $f -Value "import Link from 'next/link';"
Add-Content $f -Value "import { usePathname } from 'next/navigation';"
Add-Content $f -Value "import { cn } from '@/lib/utils';"
Add-Content $f -Value "import { LayoutDashboard, Users, ClipboardList, HelpCircle, BarChart3, Settings, Laptop, LogOut } from 'lucide-react';"

Add-Content $f -Value "const navItems = ["
Add-Content $f -Value "  { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, roles: ['admin','employee'] },"
Add-Content $f -Value "  { href: '/employees', label: 'Employees', icon: Users, roles: ['admin'] },"
Add-Content $f -Value "  { href: '/onboarding', label: 'Onboarding', icon: ClipboardList, roles: ['employee'] },"
Add-Content $f -Value "  { href: '/requests', label: 'Requests', icon: HelpCircle, roles: ['admin','employee'] },"
Add-Content $f -Value "  { href: '/analytics', label: 'Analytics', icon: BarChart3, roles: ['admin'] },"
Add-Content $f -Value "  { href: '/assistant', label: 'Ask AI', icon: Laptop, roles: ['employee'] },"
Add-Content $f -Value "  { href: '/settings', label: 'Settings', icon: Settings, roles: ['admin','employee'] },"
Add-Content $f -Value "];"

Add-Content $f -Value "export function Sidebar({ role, onClose }: { role: string; onClose?: () => void }) {"
Add-Content $f -Value "  const pathname = usePathname();"
Add-Content $f -Value "  const filtered = navItems.filter(item => item.roles.includes(role));"
Add-Content $f -Value "  return ("
Add-Content $f -Value "    <div className='flex h-full flex-col bg-indigo-950 text-white'>"
Add-Content $f -Value "      <div className='flex h-16 items-center gap-2 px-6 border-b border-indigo-800'>"
Add-Content $f -Value "        <div className='h-8 w-8 rounded-lg bg-indigo-500 flex items-center justify-center text-sm font-bold'>O</div>"
Add-Content $f -Value "        <div>"
Add-Content $f -Value "          <p className='text-sm font-semibold'>OnboardAI</p>"
Add-Content $f -Value "          <p className='text-xs text-indigo-300'>Employee Onboarding</p>"
Add-Content $f -Value "        </div>"
Add-Content $f -Value "      </div>"
Add-Content $f -Value "      <nav className='flex-1 space-y-1 p-4 overflow-y-auto'>"
Add-Content $f -Value "        {filtered.map((item) => {"
Add-Content $f -Value "          const Icon = item.icon;"
Add-Content $f -Value "          const active = pathname === item.href || pathname.startsWith(item.href + '/');"
Add-Content $f -Value "          return ("
Add-Content $f -Value "            <Link"
Add-Content $f -Value "              key={item.href}"
Add-Content $f -Value "              href={item.href}"
Add-Content $f -Value "              onClick={onClose}"
Add-Content $f -Value "              className={cn("
Add-Content $f -Value "                'flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors',"
Add-Content $f -Value "                active"
Add-Content $f -Value "                  ? 'bg-indigo-800 text-white'"
Add-Content $f -Value "                  : 'text-indigo-200 hover:bg-indigo-800/50 hover:text-white'"
Add-Content $f -Value "              )}"
Add-Content $f -Value "            >"
Add-Content $f -Value "              <Icon className='h-5 w-5 flex-shrink-0' />"
Add-Content $f -Value "              {item.label}"
Add-Content $f -Value "            </Link>"
Add-Content $f -Value "          );"
Add-Content $f -Value "        })}"
Add-Content $f -Value "      </nav>"
Add-Content $f -Value "      <div className='p-4 border-t border-indigo-800'>"
Add-Content $f -Value "        <Link href='/login' className='flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-indigo-200 hover:bg-indigo-800/50 hover:text-white transition-colors'>"
Add-Content $f -Value "          <LogOut className='h-5 w-5 flex-shrink-0' />"
Add-Content $f -Value "          Sign Out"
Add-Content $f -Value "        </Link>"
Add-Content $f -Value "      </div>"
Add-Content $f -Value "    </div>"
Add-Content $f -Value "  );"
Add-Content $f -Value "}"
Write-Host "sidebar.tsx written"